---------------------2019-06-21 13:26:54---------------------
Traceback (most recent call last):
  File "manager-x.py", line 354, in <module>
    reguler.act(cache)
  File "manager-x.py", line 324, in act
    F()
  File "<string>", line 2, in updatebackground
  File "/usr/lib/python3.7/multiprocessing/managers.py", line 811, in _callmethod
    raise convert_to_error(kind, result)
requests.exceptions.SSLError: None: Max retries exceeded with url: /HPImageArchive.aspx?n=1&format=js (Caused by None)
